clc
clear all
close all

for File_path = 1:3
    path_name = append('E:\THESIS\SEED_IV_METHOD\METHOD5.2_FILE\07.CONVERT2STR\',num2str(File_path));
    TRAIN_TRAIN_CONVERT2STR_name = append(path_name,'\TRAIN_TRAIN_CONVERT2STR.mat');
    TRAIN_TRAIN_CONVERT2STR_load = load(TRAIN_TRAIN_CONVERT2STR_name);
    TRAIN_TRAIN_CONVERT2STR = TRAIN_TRAIN_CONVERT2STR_load.TRAIN_TRAIN_CONVERT2STR;
    SIZE_TRAIN_TRAIN_CONVERT2STR = size(TRAIN_TRAIN_CONVERT2STR,1);
    K_FOLD = 4;
    PRECENT_TRAIN_TEST = 100/K_FOLD;
    SIZE_TRAIN_TEST = SIZE_TRAIN_TRAIN_CONVERT2STR*(PRECENT_TRAIN_TEST/100);
    SIZE_TRAIN_TRAIN = SIZE_TRAIN_TRAIN_CONVERT2STR - SIZE_TRAIN_TEST;
    NEXT_FOLD = 0;
    FINISH_COUNT_FOLD = 0
    for NUM_K_FOLD = 1:K_FOLD
        TRAIN_TRAIN = TRAIN_TRAIN_CONVERT2STR;
        for SAMPLE_TRAIN_TEST = 1:SIZE_TRAIN_TEST
            TRAIN_TSET{SAMPLE_TRAIN_TEST,1} = TRAIN_TRAIN_CONVERT2STR{SAMPLE_TRAIN_TEST+NEXT_FOLD,1};
            TRAIN_TRAIN{SAMPLE_TRAIN_TEST+NEXT_FOLD,1} = {};
        end
        for SAMPLE_TRAIN_TRAIN = 1:SIZE_TRAIN_TRAIN_CONVERT2STR
            if SAMPLE_TRAIN_TRAIN <= SIZE_TRAIN_TRAIN
                CHECK_EMPTY = isempty(TRAIN_TRAIN{SAMPLE_TRAIN_TRAIN,1});
                if CHECK_EMPTY == 1
                    TRAIN_TRAIN{SAMPLE_TRAIN_TRAIN,1} = TRAIN_TRAIN{SAMPLE_TRAIN_TRAIN+SIZE_TRAIN_TEST,1};
                    TRAIN_TRAIN{SAMPLE_TRAIN_TRAIN+SIZE_TRAIN_TEST,1} = {};
                else
                    TRAIN_TRAIN{SAMPLE_TRAIN_TRAIN,1} = TRAIN_TRAIN{SAMPLE_TRAIN_TRAIN,1};
                end
            end
        end
        for SAMPLE_TRAIN_TEST = 1:SIZE_TRAIN_TEST
            STR_TRAIN_TSET = TRAIN_TSET{SAMPLE_TRAIN_TEST,1};
            for SAMPLE_TRAIN_TRAIN = 1:SIZE_TRAIN_TRAIN
                CHECK_EMPTY = isempty(TRAIN_TRAIN{SAMPLE_TRAIN_TRAIN,1});
                if CHECK_EMPTY == 0
                    STR_TRAIN_TRAIN = TRAIN_TRAIN{SAMPLE_TRAIN_TRAIN,1};
                    EDIT_DISTANCE(SAMPLE_TRAIN_TRAIN,SAMPLE_TRAIN_TEST) = EditDistance(STR_TRAIN_TRAIN,STR_TRAIN_TSET);
                end
            end
        end
        EDIT_DISTANCE_FOLD{NUM_K_FOLD,1} = EDIT_DISTANCE;
        NEXT_FOLD = NEXT_FOLD+SIZE_TRAIN_TEST;
        FINISH_COUNT_FOLD = FINISH_COUNT_FOLD+1
    end
    %% SAVE_DATA
    create_path = append('E:\THESIS\SEED_IV_METHOD\METHOD5.2_FILE\08.CROSS_VALIDATION\',num2str(File_path));
    create_EDIT_DISTANCE_FOLD = append(create_path,'\EDIT_DISTANCE_FOLD.mat');
    mkdir(create_path)
    save(create_EDIT_DISTANCE_FOLD,'EDIT_DISTANCE_FOLD','-v7.3')
end