clc
clear all
close all

for File_path = 1:3
    path_name = append('E:\THESIS\RESULT\SEED_IV\METHOD01\07.CONVERT2STR_62\',num2str(File_path));
    TRAIN_TRAIN_CONVERT2STR_name = append(path_name,'\TRAIN_TRAIN_CONVERT2STR.mat');
    TRAIN_TRAIN_CONVERT2STR_load = load(TRAIN_TRAIN_CONVERT2STR_name);
    TRAIN_TRAIN_CONVERT2STR = TRAIN_TRAIN_CONVERT2STR_load.TRAIN_TRAIN_CONVERT2STR;
    CHECK_REPEATER = [];
    for CUL_TRAIN_TRAIN = 1:size(TRAIN_TRAIN_CONVERT2STR,1)
        CUL_SAMPLE = TRAIN_TRAIN_CONVERT2STR{CUL_TRAIN_TRAIN,1};
        for ROW_TRAIN_TRAIN = 1:size(TRAIN_TRAIN_CONVERT2STR,1)
            ROW_SAMPLE = TRAIN_TRAIN_CONVERT2STR{ROW_TRAIN_TRAIN,1};
            CHECK_REPEATER(ROW_TRAIN_TRAIN,CUL_TRAIN_TRAIN) = F01_EditDistance(ROW_SAMPLE,CUL_SAMPLE);
        end
    end
    CHECK_REPEATER_FILE{File_path,1} = CHECK_REPEATER;
end
%% SAVE_DATA
create_path = append('E:\THESIS\RESULT\SEED_IV\METHOD01\08.CHECK_REPEATER_62');
create_CHECK_REPEATER_FILE = append(create_path,'\CHECK_REPEATER_FILE.mat');
mkdir(create_path)
save(create_CHECK_REPEATER_FILE,'CHECK_REPEATER_FILE','-v7.3')